--- #YAML:1.0
name:               File-Fetch
version:            0.21_02
abstract:           Generic file fetching code
author:
    - Jos Boumans <kane[at]cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Basename:       0
    File::Copy:           0
    File::Path:           0
    File::Spec:           0.82
    IPC::Cmd:             0.42
    Locale::Maketext::Simple:  0
    Module::Load::Conditional:  0.04
    Params::Check:        0.07
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
