# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Fetch
version:      0.07
version_from: lib/File/Fetch.pm
installdirs:  site
requires:
    File::Basename:                0
    File::Copy:                    0
    File::Path:                    0
    File::Spec:                    0.82
    IPC::Cmd:                      0.04
    Locale::Maketext::Simple:      0
    Module::Load::Conditional:     0.04
    Params::Check:                 0.07
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
